name: portofolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  google_fonts: ^6.1.0
  url_launcher: ^6.2.3
  provider: ^6.1.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/befriend2.png
    - assets/full_resume.pdf
